### ISSUE TITLE
Question: How to handle marker/cluster removal efficiently

### ISSUE THREAD

**Issue by cwsiteplan** [p-lr/MapCompose#100]
Hi,

I do have the ability to add/remove (show/hide) clusters as well as to add/remove markers.

Currently the ViewState (which markers/clusters to show) is coming from a state object (ViewModel)
on update of the state i do manipulate the mapState (which is living in the Composable) with `addMarker()`
Problem is now how to remove items that are no longer part of the new ViewState.

I'd somehow remember previous marker- and cluster-Ids  and do a diff with the new viewState in order to call `removeMarker/Cluster(id)` - is there a more elegant solution to that?

Removing all markers is not an options as most of the time only a small part of the markers change.

**Comment by p-lr** [comment]
Hi,

You don't need to maintain a list of added markers. You can get a readonly state of MapState's markers using either:
`markerDerivedState` or `markerSnapshotFlow` apis, depending on your usage.
Basically, you can know the list of markers at a given point in time, or react on it when the list changes.

In your case, when the state in your ViewState changes, you can make a diff between your new list and the list you get with `markerDerivedState`. Then, you know which markers to add/remove.

As side note, while you can remove a marker using `removeMarker`, you cannot remove a cluster explicitly. You can remove a cluster**er**, using `removeClusterer` api.

**Comment by cwsiteplan** [comment]
thank you for the clarification!

**Comment by cwsiteplan** [comment]
as there is no information on current clusterIds it seems i still need to maintain a list of added clusters to do the diffing in the end.

**Comment by p-lr** [comment]
Could you elaborate on your need to know the current list of clusters?
For example, the api doesn't offer a way to remove a cluster directly because then what would be the exected behavior regarding the associated markers? Are you expecting them to be removed?

**Comment by cwsiteplan** [comment]
yes, it would be basically the as as with individual markers.
i'd want to show/hide entire clusters (managers with their markers)

**Comment by p-lr** [comment]
How do you get the id of a cluster to hide? By tapping on it?

**Comment by cwsiteplan** [comment]
it's again a diff from the state.
getting a new UI state with the clusters that should be visible.
then removing the ones which are not part of the new state.

**Comment by cwsiteplan** [comment]
my UI state (which clusters to show) is also influenced by other places (not only the user interacting with it)
therefore i'd need either something like the derived-state for existing cluster(manager)s or I maintain the list of current clusters by hand

**Comment by p-lr** [comment]
the cluster state is a **derived state** of the markers state. Depending on the scale, clusters will be formed and removed, markers will be moved in or out of clusters, etc. Clusters state isn't something to be manipulated directly. 
Changing the state of markers will in turn change the state of clusters.
Before we discuss the need for a  derived-state for existing clusters, can you confirm that you understand that ?

**Comment by cwsiteplan** [comment]
i see - thanks for clarification.

then i would refer to clusterManagers (and their associated markers).
i do see/use clusterManagers to group types of markers and with the managers i'd like to show hide specific groups.

"grouping" markers could be done with prefixes of their id's as well - in order to show/hide a specific group, but i thought using clusters (as i anyways also want to cluster only the distinct groups) would serve both.

**Comment by p-lr** [comment]
do you mean clusteter when you talk about "clusterManager"? I don't use the later term in the api.

**Comment by cwsiteplan** [comment]
yep, sorry - was referring to the `Clusterer`
