### ISSUE TITLE
Bug: Marker size (width) is limited to screen width

### ISSUE THREAD

**Issue by cwsiteplan** [p-lr/MapCompose#105]
Hi,

I'm drawing an accuracy circle around the users current location.
It can happen that the user can zoom in so far that the accuracy circle would exceed the device width.
Here the bug happens as the circle (marker content) is somehow capped to the display width and the marker circle is getting oval.

See video:
[circle-bug.webm](https://github.com/p-lr/MapCompose/assets/141158723/fc745119-cb5b-4ef1-bc87-aeef2047add7)

I adapted the sample app to showcase that: https://github.com/p-lr/MapCompose/compare/master...cwsiteplan:MapCompose:bug/max-marker-width

**Comment by p-lr** [comment]
You can fix that by using `requiredSize` instead of `size`:

```kotlin
@Composable
fun CircleMarker(size: Dp) {
    Box(Modifier.requiredSize(size).clip(CircleShape).background(Color.Red))
}
```

**Comment by cwsiteplan** [comment]
that works fine! thank you 🙏
