### ISSUE TITLE
Problem: Click callback uses outdated data

### ISSUE THREAD

**Issue by cwsiteplan** [p-lr/MapCompose#106]
Hi,

i ran into a strange issue using the marker click callback.

Pushed a sample here: https://github.com/p-lr/MapCompose/compare/master...cwsiteplan:MapCompose:bug/marker-click-callback

I'm adding a click callback to the mapState initially and inside the callback i do access data that does change over time.
But somehow the callback accesses only the initially passed object.

Interestingly, [moving the code outside the child composable](https://github.com/p-lr/MapCompose/compare/master...cwsiteplan:MapCompose:bug/marker-click-callback-flat) it starts to work fine 🤔 

Probably not related to your implementation at all, but would be glad if you have an idea why.

**Comment by p-lr** [comment]
You probably need to update the callback when your state changes. Try with:
```kotlin
@Composable
fun MyMapComposable(modifier: Modifier = Modifier, myData: MyData, mapState: MapState) {
    LaunchedEffect(myData) {
        mapState.onMarkerClick { id, x, y ->
            Log.d("Bug", "my marker state: ${myData.someList.size}")
        }
    }

    MapUI(modifier, state = mapState)
}
```

**Comment by cwsiteplan** [comment]
yep, that works too - but i'm not quite sure why i would need to do that .

**Comment by p-lr** [comment]
That's because `LaunchedEffect` can take keys as parameters, and whenever one keys changes of value, the composable block is recomposed. By using `LaunchedEffect(Unit){..}`, you are actually capturing the initial value of your state.

**Comment by cwsiteplan** [comment]
thanks, i thought i'm aware of the concept of `LaunchedEffect` but assumed that the created callback (lambda) would still access the current state - seems it also captures a snapshot of the current state -interesting.

**Comment by p-lr** [comment]
Another approach is to call a method from the view-model from the lambda, passing `id`, `x` and `y` values. Since the view-model has all necessary data, you can do necessary operations and state changes from there, without having to worry about updating the lambda.

**Comment by cwsiteplan** [comment]
just to add on that.

i ran into the issue that i was setting up click callbacks in the ViewModel.

i had 

```
map.onMarkerClick {
  callbackThatDoesComposeNavigation(...)
}
```

this resulted now in crashes when e.g. the screen was rotated and through the UI recreation a new navigator instance is created, but the viewModel still holds onto the old navigator.

solution again, is to update the click callback when the navigator changes, but just wanted to point that out for others.
