### ISSUE TITLE
[Feature Request] Support for vector tiles

### ISSUE THREAD

**Issue by rkreienbuehl** [p-lr/MapCompose#113]
Are there any plans to also support vector tiles and not only raster tiles in the future?

**Comment by p-lr** [comment]
This isn't the responsibility of MapCompose. Support for vector tiles is an implementation detail of the `TileStreamProvider`, which can return streams of `Bitmap` after a renderer converts mvt data to an image.
However, I am yet to find a way to do this natively on Android. So far, I haven't found a native renderer, while a lot of javascript implementations exist.

**Comment by rkreienbuehl** [comment]
Ok, I see. Thanks for the answer.
