### ISSUE TITLE
Undesired scroll behavior at lower scale ratios after device rotation

### ISSUE THREAD

**Issue by algostrat** [p-lr/MapCompose#122]
I've initialized MapState with a scale of 0f for a tile map to ensure the initial view displays the entire map. It uses the default MinimumScaleMode.Fit. After rotating the device, the tile map shifts either to the left or top, depending on whether the initial orientation was portrait or landscape, thus failing to maintain the center of the image.

I believe this shift occurs due to how SetScroll is recalculated within ZoomPanRotateState.onSizeChanged.  On larger scale ratios, the center of the image is maintained after device rotation as the code is intended. It looks as if the calculations aren't friendly for scales < 1.

https://github.com/p-lr/MapCompose/blob/dd015ac4c1e8588cd41e6edec24defb8e27c1da5/mapcompose/src/main/java/ovh/plrapps/mapcompose/ui/state/ZoomPanRotateState.kt#L538

**Comment by p-lr** [comment]
Could you reproduce the behavior you describe in a fork of the demo app?
It will be easier to investigate.

**Comment by p-lr** [comment]
I could reproduce the issue, thanks. I'll look into this.

**Comment by p-lr** [comment]
You were right, the problem was indeed in `ZoomPanRotateState.onSizeChanged()`

**Comment by algostrat** [comment]
> You were right, the problem was indeed in `ZoomPanRotateState.onSizeChanged()`

Thanks. When do you plan to include this commit in a new release?

**Comment by p-lr** [comment]
The version 2.12.12 is being published.
