### ISSUE TITLE
Markers are clipped to a circle

### ISSUE THREAD

**Issue by Nohus** [p-lr/MapCompose#4]
Composables added as markers are not displayed fully. Instead they are clipped to a circle shape.

With this composable:
```Kotlin
Box(Modifier.size(20.dp).background(Color.Black))
```

The bottom shape is how it displays normally, and the upper shape is the same composable showing as a marker:

![image](https://user-images.githubusercontent.com/11064768/142762193-f859b54f-94d8-4c48-920d-295df934b9ac.png)

**Comment by peterLaurence** [comment]
Indeed. It can be removed, but I need to supply an API to add it if that effect is intended.
