### ISSUE TITLE
Map is buggy when used in a dynamic size ComposeView

### ISSUE THREAD

**Issue by Nohus** [p-lr/MapCompose#47]
I have reproduced a bug on the branch `bug_reproduction_composeview`. I am not sure what exactly causes it, but it only happens when the `ComposeView` with the map in an XML layout has parent-dependent sizing (either `match_parent`, or `0dp` with constraints in a `ConstraintLayout`). In the included XML file, if you either set the layout_width of the `ComposeView` to a constant value, the issue is gone. If you set the width of the parent `FrameLayout` to a constant value, the issue is also gone.

Video below (I am attempting to scroll):

https://user-images.githubusercontent.com/11064768/149862349-1bbb9743-df36-4eab-82b5-3297c780a50a.mp4

**Comment by p-lr** [comment]
Looks like a bug in Compose. I issued a bug here : https://issuetracker.google.com/issues/215032018

**Comment by Nohus** [comment]
Sorry for not replying, in my case I changed my design a little so that the parent view layout has a fixed size.

**Comment by p-lr** [comment]
Change of design is indeed a good way to go, thanks for the feedback.
