### ISSUE TITLE
ConcurrentModificationException in TileCanvasState

### ISSUE THREAD

**Issue by Nohus** [p-lr/MapCompose#48]
I saw crash in `TileCanvasState`, in the `evictAll()` method:

```Kotlin
private fun evictAll() {
    val iterator = tilesCollected.iterator()
    while (iterator.hasNext()) {
        val tile = iterator.next() // Here
        iterator.remove()
        tile.recycle()
    }
}
```

It's a `ConcurrentModificationException` while calling `iterator.next()`. It's a crash report from one user so far, but reporting for visibility.

**Comment by p-lr** [comment]
I could reproduce this issue.
