### ISSUE TITLE
Zoom In at highest Zoomlvl. 

### ISSUE THREAD

**Issue by christianroyal** [p-lr/MapCompose#49]
Loving this library.  Is there a way at the highest scale of the map to continue to zoom into the image or is this functionality not supported.  

When I am getting to a zoom level of 4 in my application I can not go further zooming in on this level to inspect each tile in depth, would I need to somehow take my tiling library and have it supply a further zoom level to achieve this? 

*Isn't really an issue more of a question.

**Comment by p-lr** [comment]
There's an api to set the maximum scale. When creating your `MapState` instance, use `maxScale` inside the initial values block. For example:

```kotlin
MapState(4, 4096, 4096) {
    maxScale(8f)
    scroll(0.5, 0.5)
    scale(1f)
}
```
