### ISSUE TITLE
`setScrollOffsetRatio` not working properly

### ISSUE THREAD

**Issue by JerryLocke** [p-lr/MapCompose#51]
I want to achieve the following effects: 

> Here is a pin on the map, users can move the map to select any point in the map, including four corners of the map

So I tried adding this line in file `SimpleDemoVM.kt` of demo module, and I want to achieve the effect similar to `setPanLimit(SubsamplingScaleImageView.PAN_LIMIT_CENTER)` in [SubsamplingScaleImageView](https://github.com/davemorrissey/subsampling-scale-image-view):

<img width="735" alt="image" src="https://user-images.githubusercontent.com/5669245/154454638-89efb04e-006f-4fdc-b63e-2cb8bcc501f6.png">

When I run the code, I found that the effect is not like I imagined, especially after I scaled the map, the effect is more outrageous.

So I search for the code in the library to try to find the problem, and I found the following suspicious snippet:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/5669245/154459007-bdda2285-5e70-4e5e-b62e-fb88173dcc5b.png">

But unfortunately, even if I have modified the above code, `setScrolloffSetratio` still not working properly.

**Comment by p-lr** [comment]
What you outlined is definitely suspicious. I'll have a look.
However:
> When I run the code, I found that the effect is not like I imagined, especially after I scaled the map, the effect is more outrageous.

Could you explain with more details what you want to achieve?

**Comment by JerryLocke** [comment]
Here is my code: 

```kotlin
fun MapDemoSimple(
    modifier: Modifier = Modifier, viewModel: SimpleDemoVM = viewModel()
) {
    Box(modifier = modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
        MapUI(
            modifier = Modifier
                .fillMaxSize(),
            state = viewModel.state,
        ) {
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                // A blue pin in map Center (Wrong)
                Icon(
                    painterResource(id = R.drawable.pin),
                    contentDescription = null,
                    modifier = Modifier.placeCenter(),
                    tint = Color.Blue,
                )
            }
        }

        // A red pin in view center (Correct)
        Icon(
            painterResource(id = R.drawable.pin),
            contentDescription = null,
            modifier = Modifier.placeCenter(),
            tint = Color.Red,
        )
    }
}

private fun Modifier.placeCenter() = layout { measurable, constraints ->
    val measured = measurable.measure(constraints)
    layout(measured.width, measured.height) {
        measured.placeRelative(0, -(measured.height / 2F).roundToInt())
    }
}
```

I created two pins on the screen, one is red, always in the middle of the view, one is blue, always in the middle of the map.

Under normal circumstances, these two pins should completely coincide.

But once I scaled, these two pins are separated, especially in some scaling, two right corners of the map can move more than the blue pin(see the 26' in the video).

https://user-images.githubusercontent.com/5669245/154607276-5060d9ed-7a04-4efd-bd0c-9cabdda5c56f.mp4

**Comment by JerryLocke** [comment]
Please forgive my poor expressive ability, thank you for your patience to read my issue.

I know how to use the marker API, the reason why I made a child composable instead of using the marker API is just to make it easier to figure out where is the real center of `MapUI` after adding padding.

Simply put, I just want to achieve a [PAN_LIMIT_CENTER ](https://github.com/davemorrissey/subsampling-scale-image-view/wiki/07.-Configuration#setpanlimitint) effect similar to `SubsamplingScaleImageView`.

After I tried setting `minimumScaleMode = Fill` as you said at the end, I finally got what I wanted, THANKS a lot!


PS: 

The reason why I want to do this is because I want to achieve such a requirement: 

> Suppose there is a user who wants to accurately select any coordinate on the map (including the coordinates at the edges), that red pin is to indicate the coordinate that the user wants to select.

BTW, human fingers are usually thick, it is difficult to accurately click on a accurately position through the touch screen, especially at the edges of the map. But it is easier for the user to accurately select a point by moving the basemap so that the pin (which remains in a fixed position all the way) is indirectly placed where they want to select.

**Comment by p-lr** [comment]
No worries. Glad you sorted that out.
If your goal is to make the edges precisely reachable, there's an alternate approach, using only the marker api.

Below a screenshot from an app I develop using MapCompose. You can see there's a maker at the top right of the map, which the user is currently positioning. Since we can't move  the finger to the edge, a another marker which is bigger (the blue circle) is used to move the red marker. In other works, the blue marker is draggable (MapCompose allows you to do that). When we move the blue marker, the red marker is moved along and stays at the center of the blue marker. You can imagine than now it's possible to place the red marker at the edge.

![image](https://user-images.githubusercontent.com/15638794/154679974-eafc835f-f376-4069-b721-6362c38d8d67.png)
