### ISSUE TITLE
Marker and map blinks and shifts with BottomNavigationView

### ISSUE THREAD

**Issue by TheBrisingers** [p-lr/MapCompose#52]
I am having a visual problem when I want to display a map while having a `BottomNavigationView` also displayed (see video). The points and map fragments seem to shift as if their position was recalculated.

https://user-images.githubusercontent.com/71455883/155365145-6b766fbb-8a55-4749-9f90-3bcdbd25b6cc.mp4

The problem disappears if you change the `visibility` of the `BottomNavigationView` to `GONE`. 

I specify that I work in a `ComposeView` in fragment xml because my application does not implement Compose. So I have :

```
Activity {
	FragmentContainer {
		MyFragment {
			ComposeView {
				MapCompose {}
			}
		}
	}
	BottomNavigationView {}
}
```

**Comment by p-lr** [comment]
@TheBrisingers Have you found a workaround for this issue?
