### ISSUE TITLE
Click listener on the map, e.g. to add marker

### ISSUE THREAD

**Issue by cypher447** [p-lr/MapCompose#63]
It would be a nice feature, to have a click/longclick listener on the map, like in OSMdroid and GMaps. It should be fired when clicking on an empty space in the map and allow access to the click position. A common usecase for this is adding a marker at an empty position.

**Comment by p-lr** [comment]
I completely forgot, but there's already an api for tap gestures using `MapState.onTap(tapCb: (x: Double, y: Double) -> Unit)`.
