### ISSUE TITLE
Map padding

### ISSUE THREAD

**Issue by TimPushkin** [p-lr/MapCompose#65]
Currently the map cannot be scrolled any further when its end reaches the corresponding end of the screen. For example, if I zoom in I can scroll left only until the left end of the map reaches the left end of the display.

The problem is that it is not very convenient for a user to see some part of the map that is really close to the map's border, especially when there is some other UI on top of the map close to the corresponding end of the screen.

The solution might be to add an ability to control what portion of the screen can the map's border be additionally scrolled after its border reaches the corresponding end of the screen. For example, 0 would be the current behavior, 0.5 would let the border reach the center of the screen, and 1 would let it reach the opposite end of the screen.

The problem that I see with this solution is that it will allow the map to be scrolled even when it is fully zoomed out, so maybe some additional restrictions are required.

**Comment by p-lr** [comment]
Have you tried the `MapState.setScrollOffsetRatio(xRatio: Float, yRatio: Float)` api?
It should do what you describe.
However, it doesn't play nice when the map is fully zoomed out.

**Comment by TimPushkin** [comment]
Exactly what I wanted, thanks!
