### ISSUE TITLE
Access `minScale` property of `MapState`

### ISSUE THREAD

**Issue by TimPushkin** [p-lr/MapCompose#70]
`MapState` has public property `maxScale` but does not have `minScale`, even though `ZoomPanRotateState` has it (as a private property). It would be great to make it accesible for reading from `MapState` as it can be set to some non-trivial values by `Fit` or `Fill` `MinimumScaleMode`s. Personally I need this for some scale-dependent animations to normalize the scale.

**Comment by p-lr** [comment]
I believe the reason why the `minScale` hasn't been added is, as you mention, because it depends on other inputs such as `MinimumScaleMode`. However, it should be possible to have the `minScale` backed by a State, or accessible as a Flow. I will have a look.

**Comment by p-lr** [comment]
I've created the branch `min-scale`, where I added two apis :
- one the get the current min scale
- one the get the min scale as a Flow

If it's ok for you I'll merge

**Comment by TimPushkin** [comment]
@p-lr Could you please publish the current library version to Maven?

**Comment by p-lr** [comment]
@TimPushkin It's done, and should be available on maven servers in 1 hour or so.
