### ISSUE TITLE
Is it possible to use GeoJSON and Vector tiles?

### ISSUE THREAD

**Issue by thegrxp** [p-lr/MapCompose#72]
Thank you for your amazing work!

**Comment by p-lr** [comment]
For GeoJSON, your implementation of `TileStreamProvider` can fetch the relevant tile in a geoJSON file.
All you need is a library or custom code to deal with that kind of file.

Regarding vector tiles, you need a renderer to convert a vector tile into an image. The `TileStreamProvider` is expected to return a `InputStream` of an image. Again, you will need a library for that.

**Comment by thegrxp** [comment]
Ok nice, thank you for the info
