### ISSUE TITLE
Two fingers tap should be easier to trigger

### ISSUE THREAD

**Issue by p-lr** [p-lr/MapCompose#76]
For now, the gesture has to be almost perfect. The two fingers should tap the screen at almost the same time, not move from even one pixel, and be released altogether.
The gesture detection should be move permissive.

**Comment by p-lr** [comment]
@TimPushkin I've created to branch `try-fix-#76`. Could you try it out and tell me if that fixes the issue for you?

**Comment by TimPushkin** [comment]
Tried it, now it works nicely
