### ISSUE TITLE
Paths have no way to specify ending "caps"

### ISSUE THREAD

**Issue by Nohus** [p-lr/MapCompose#86]
Drawn paths end with a sharp cut off:

![image](https://github.com/p-lr/MapCompose/assets/11064768/fb790b59-5dbd-4b70-844d-18bc3ae94d39)

When using the Google Maps Compose library, you are able to specify how paths end, with the `startCap` and `endCap` parameters: https://googlemaps.github.io/android-maps-compose/maps-compose/com.google.maps.android.compose/-polyline.html

Here is an example of a path in Google Maps Compose using `RoundCap`. Notice how the end of the line is nicely rounded:

![image](https://github.com/p-lr/MapCompose/assets/11064768/a1048a8e-8e55-45c4-9149-829014604494)

**Comment by p-lr** [comment]
This can be done bit the implementation will depend on #85
