### ISSUE TITLE
Question: Tiles with padding

### ISSUE THREAD

**Issue by cwsiteplan** [p-lr/MapCompose#93]
Hi,

first of all - thanks for all the work! Really appreciate that.

I'm having map tiles that do have a certain padding (vertical and horizontal) applied to them (the border tiles - this is necessary when map tiles are created from non-uniform sizes so we can get 256x256 tiles). Unfortunately i cannot change the tiling source - so i need to respect (remove) that padding when rendering the tiles/map. Basically shrinking the viewport by the amount of the padding.

<img width="484" alt="image" src="https://github.com/p-lr/MapCompose/assets/141158723/ba5924fb-81eb-46a9-bf01-e32ae8bd6eb9">

> (note: all tiles still use a 256x256 ratio- this sketch is a bit misleading)

Would there be an easy way of adjusting that without forking the lib? if not - could you point me to the corresponding code so i can implement that (probably creating a PR if this could be helpful to others as well).

**Comment by cwsiteplan** [comment]
mhm - just saw https://github.com/p-lr/MapCompose/pull/59
maybe that helps already - will investigate

**Comment by cwsiteplan** [comment]
i tried now to add the scaled padding as `absoluteOffset` to the marker. which seems to work fine on a single render, but upon zooming these offsets seem to cause glitches - see video below

https://github.com/p-lr/MapCompose/assets/141158723/d5c25683-1721-4e70-a097-8b0d87da0d3d

**Comment by p-lr** [comment]
Hi,
I'll be able to look into this in a few days.

**Comment by p-lr** [comment]
If I understand correctly, you want to constrain the scroll so that only the blue part of the canvas is visible. Do you confirm?
Is is possible for you to fork the lib and edit one of the demo with your tile source? It would be useful for me to test necessary changes.

**Comment by cwsiteplan** [comment]
Yes, but it's not only the "scroll" - the whole canvas of the map should be constrained to that. as placing markers would also be a bit messy if i need to calculate padding offsets.

Will do a fork and update you on that 👍

**Comment by cwsiteplan** [comment]
i've now added a map source that contains the padded tiles in the `Simple demo` screen.
[here's the fork](https://github.com/cwsiteplan/MapCompose/tree/feature/tile-padding).

note: the padding of the tiles differs on the different zoom levels as we need to fit the Images to the nearest multiple of 256.

thanks for having a look!

**Comment by p-lr** [comment]
Good job finding a solution.
I'm aware that this feature can be useful, but don't want to incorporate this - at least for now. The reason is: it as to be fully supported. For the rendering part, it already complicated a lot the `TileCanvas` implementation. Scroll constraints are already quite tricky even without this feature. Keeping the code base in a sane state is important.
Most often, it's way simpler to adapt the tile source (when possible). 

Another approach would be to transform the tile source on the fly (making bitmap stitching), so that all of this become transparent for the library.
