### ISSUE TITLE
Add lat/long versus relative support

### ISSUE THREAD

**Issue by kmbisset89** [p-lr/MapCompose#95]
This is an awesome start to a map engine. But if we had geotiff's we would have to make another application to make them in the file format necessary for this. If you allow for lat long support that would make this more expandable.

**Comment by rt-bishop** [comment]
For conversion between lat/lon and x/y(0,1) you could use something like this: 

```kotlin
fun Double.latToY01(): Double {
    val sinus = sin(clipLat(this) * PI / MAX_LONGITUDE)
    return 0.5 - ln((1 + sinus) / (1 - sinus)) / (4 * PI)
}

fun Double.lonToX01(): Double {
    return (clipLon(this) - MIN_LONGITUDE) / (MAX_LONGITUDE - MIN_LONGITUDE)
}

fun Double.y01ToLat(): Double {
    return 90 - 360 * atan(exp((this - 0.5) * 2 * PI)) / PI
}

fun Double.x01ToLon(): Double {
    return MIN_LONGITUDE + (MAX_LONGITUDE - MIN_LONGITUDE) * this
}
```

[Ref code.](https://github.com/rt-bishop/Look4Sat/blob/devel/domain/src/main/java/com/rtbishop/look4sat/domain/utility/GeoConverter.kt) I do agree though it would be great to have this inside the library with the checks for exceeding the MIN/MAX values.

**Comment by p-lr** [comment]
This library isn't tied to any measurement system. A map could be taken from a scanned paper or may represent the whole world. In the latter case, lat/lon make sense. However lat/lon may be irrelevant in other use cases.
Also, the relative to lat/lon formulas depend on the projection used to make the map.  

Please provide more details about your usage of the library.

**Comment by Nohus** [comment]
To share a use case, I'm using the library for a map that uses a different
coordinate system (EPSG:2180), so support for GPS in particular wouldn't be
useful to me, and I know many countries have their own coordinate systems
for their maps.

Where a case could be made, is to have the library accept a conversion
interface so you can then use your own coordinate system and have the
library call your conversion internally. But I don't think it would be that
much more useful than just doing it yourself.

**Comment by p-lr** [comment]
Typically you know the extent in latitude and longitude of what you're rendering. Let's say `Ya` and `Yb` are respectively the projected coordinate in Y dimension of the top and the bottom. When `y` is a relative coordinate, it's projected coordinate in Y dimension is is `Ya + `y`*(`Yb`-`Ya`). Then, the corresponding longitude is obtained using the relevant formula (which depends on the projection).

**Comment by kmbisset89** [comment]
I am not sure I understand completely but I will try my best to see what I can do.

**Comment by kmbisset89** [comment]
I think I will have to split bitmaps over a projection.
