### ISSUE TITLE
Marker composable content update

### ISSUE THREAD

**Issue by cwsiteplan** [p-lr/MapCompose#99]
Hi,

I do have a marker content that is dependent on the rotation of the map. (potentially 100s of markers)
Seems like there currently no other way to update the marker content as to remove the marker and add it again?

There is no recomposition of the content dependent on it's parameters happening.

A GoogleMap Marker has the ability to define `key`s which are then used to recompose the marker if one of the keys changes.
Would it be possible to implement something like that?

**Comment by cwsiteplan** [comment]
I adapted a demo to showcase my use case.
(rotation would be then actually used by the compass of the phone)

https://github.com/cwsiteplan/MapCompose/commit/088f2d9c4cb692286865138af4d88e88163ab047

**Comment by p-lr** [comment]
Hi,

This [discussion](https://github.com/p-lr/MapCompose/discussions/89) answers a similar question.

**Comment by cwsiteplan** [comment]
Hi,
thank you for the quick response 🚀 . that worked for me 👍
